### ISSUE TITLE
install node for linux machine

### ISSUE THREAD

**Issue by maddevred** [SEI-ATL/UNIT_2#11]
![Screenshot from 2020-11-12 14-11-21](https://user-images.githubusercontent.com/73178321/98985224-3f246480-24f1-11eb-9067-6b36d7d75efa.png)

**Comment by pmacaluso3** [comment]
What output do you get when you run `node -v`?

**Comment by marjames98** [comment]
@pmacaluso3 
![Screenshot from 2020-11-12 14-42-22](https://user-images.githubusercontent.com/73178321/98988366-8dd3fd80-24f5-11eb-830e-43aa2ec388c9.png)

**Comment by maddevred** [comment]
![Screenshot from 2020-11-12 14-43-45](https://user-images.githubusercontent.com/73178321/98988395-99272900-24f5-11eb-8737-5dfcb8bc8a17.png)
