### ISSUE TITLE
Function wont display

### ISSUE THREAD

**Issue by JaxonNarramore** [SEI-ATL/UNIT_2#13]
![Screen Shot 2020-11-12 at 1 39 33 PM](https://user-images.githubusercontent.com/71084561/98987926-82300900-24ec-11eb-9982-72de37039313.png)
![Screen Shot 2020-11-12 at 1 39 52 PM](https://user-images.githubusercontent.com/71084561/98987953-8cea9e00-24ec-11eb-8579-718cfb2bc867.png)

**Comment by pmacaluso3** [comment]
Fixed?

**Comment by romebell** [comment]
Issue solved ✅
