### ISSUE TITLE
[deliverable] Node Modules Practice

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#17]
Link: https://github.com/SEI-ATL/node_modules_practice

- [ ] Complete and make `pull request` 

**Reading**
- [x] [SQL](https://romebell.gitbook.io/sei-1019/databases/sql-intro)
- [x] [SQL Cheatsheet](https://romebell.gitbook.io/sei-1019/resources/sqlcheatsheet)
- [x] [Intro to Express](https://romebell.gitbook.io/sei-1019/node-express/00readme-1/01intro-to-express)
- [x] [Express Routes](https://romebell.gitbook.io/sei-1019/node-express/00readme-1/01intro-to-express/02routes)
- [x] [Express Views](https://romebell.gitbook.io/sei-1019/node-express/00readme-1/01intro-to-express/03views)

**Comment by NykywanP** [comment]
Task complete!! [deliverable] Node Modules Practice
#17

**Comment by nitishdayal** [comment]
Done
