### ISSUE TITLE
Rome's Pod

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#19]
### Add your link to the ISSUE that you create here. Be sure to assign your Pod Leader

**Comment by canourrea23** [comment]
### Can't figure out how to get googles API 
### I signed up but I'm only getting an OAuth
### Not seeing option for Key API
### I am having trouble navigating and knowing where to look in
### youtube videos but it seem like the website has been updated since and random clicking

**Comment by fmuwanguzi** [comment]
https://github.com/fmuwanguzi/weather-app

I keep getting a cannot get error when I add /weather and I've check my routes multiple times @romebell

**Comment by canourrea23** [comment]
### I don't how to setup up to use the API
### I installed npm needed 
### ```  
errors: [
    {
      message: 'API key not valid. Please pass a valid API key.',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```
### It's something to do with my configurations or files setup is missing something
### I have tried trail and error, youtube videos

**Comment by fmuwanguzi** [comment]
I keep getting this error 
![Screen Shot 2020-11-30 at 2 48 55 PM](https://user-images.githubusercontent.com/72531389/100656761-31594680-331b-11eb-9e32-194a9101a752.png)

this is how my weather route is set up 
![Screen Shot 2020-11-30 at 2 50 19 PM](https://user-images.githubusercontent.com/72531389/100656863-62397b80-331b-11eb-9cd5-61bd79cb5b89.png)

**Comment by romebell** [comment]
@canourrea23 what API are you trying to access data from?

**Comment by romebell** [comment]
@fmuwanguzi you spelled `response` wrong on line 5

**Comment by fmuwanguzi** [comment]
@romebell that didn't change anything I'm not sure if maybe it order in which i put my code in

**Comment by canourrea23** [comment]
In creating my table I was able to create it but I keep getting a problem to migrate it. 
![Screen Shot 2020-12-01 at 10 47 21 AM](https://user-images.githubusercontent.com/73137943/100763108-c1060000-33c2-11eb-953b-a9d787436aec.png)
![Screen Shot 2020-12-01 at 10 47 08 AM](https://user-images.githubusercontent.com/73137943/100763115-c2cfc380-33c2-11eb-96e6-367ffbbebffa.png)

**Comment by canourrea23** [comment]
### I am trying to get my cities to go through the interpulation 
### Issue 
```
let searchTerm = res.newLocation;
// searchTerm = res.newLocation;
newLocation = res.Washington;
  const newLocation = {
    method: 'GET',
    url: `https://www.numbeo.com/cost-of-living/in/${newLocation}`
  };
    request({searchTerm}, (err, res, body) => {
          if (err) return console.error(err);
          let $ = cheerio.load(body);
          let title = $('tr').attr('class', 'first_currency');
    let milkPrice = Number($('.first_currency').find('span').text().split('\n')[10].split('$')[0]);
    console.log(milkPrice);
```
### I get ReferenceError: res is not defined.
### I am not requesting things correctly
### I also tried looking for another example and even this code
```
location.get('/city/:city', (req,res)=> {
  console.log(req.params.city);
  const city = req.params.Washington
  const newLocation = {
    method: 'GET',
    url: `https://www.numbeo.com/cost-of-living/in/${city}`
  };
    request({city}, (err, res, body) => {
          if (err) return console.error(err);
          let $ = cheerio.load(body);
```
and I get SyntaxError: Unexpected end of input

**Comment by romebell** [comment]
```js
let searchTerm = res.newLocation; // needs to be in a route to get access to res
newLocation = res.Washington;
  const newLocation = {
    method: 'GET',
    url: `https://www.numbeo.com/cost-of-living/in/${newLocation}`
  };
    request({searchTerm}, (err, res, body) => {
          if (err) return console.error(err);
          let $ = cheerio.load(body);
          let title = $('tr').attr('class', 'first_currency');
    let milkPrice = Number($('.first_currency').find('span').text().split('\n')[10].split('$')[0]);
    console.log(milkPrice);
```
You can only use `res` inside of a route like so:

```js
app.get("/", (req, res) => {
   console.log(res);
   res.send('Hello, Carolina');
})
```

**Comment by romebell** [comment]
Is this a route that you made inside of a `location.js` file? Double check to make sure that you have all your parenthesis is the right place.

```js
location.get('/city/:city', (req,res)=> {
  console.log(req.params.city);
  const city = req.params.Washington
  const newLocation = {
    method: 'GET',
    url: `https://www.numbeo.com/cost-of-living/in/${city}`
  };
    request({city}, (err, res, body) => {
          if (err) return console.error(err);
          let $ = cheerio.load(body);
```

**Comment by romebell** [comment]
#### Inside of your `comment` model associations, I'm thinking:
```js
models.comment.belongsToMany(models.user);
models.comment.belongsToMany(models.game);
```

#### Inside of `user` model
```js
models.user.hasMany(models.comment);
models.user.hasMany(models.game);
```

#### Inside of `game` model
```js
models.game.hasMany(models.comment);
models.game.belongTo(models.user);
```

**Comment by canourrea23** [comment]
> Is this a route that you made inside of a `location.js` file? Double check to make sure that you have all your parenthesis is the right place.
> 
> ```js
> location.get('/city/:city', (req,res)=> {
>   console.log(req.params.city);
>   const city = req.params.Washington
>   const newLocation = {
>     method: 'GET',
>     url: `https://www.numbeo.com/cost-of-living/in/${city}`
>   };
>     request({city}, (err, res, body) => {
>           if (err) return console.error(err);
>           let $ = cheerio.load(body);
> ```



> Is this a route that you made inside of a `location.js` file? Double check to make sure that you have all your parenthesis is the right place.
> 
> ```js
> location.get('/city/:city', (req,res)=> {
>   console.log(req.params.city);
>   const city = req.params.Washington
>   const newLocation = {
>     method: 'GET',
>     url: `https://www.numbeo.com/cost-of-living/in/${city}`
>   };
>     request({city}, (err, res, body) => {
>           if (err) return console.error(err);
>           let $ = cheerio.load(body);
> ```

I have it in my profile.js but that's why I did ```const city = req.params.Washington``` I thought it would plug Washington in

**Comment by romebell** [comment]
@AlexJBustillos This [line](https://github.com/AlexJBustillos/Loud-and-Green/blob/7154628623c7cc1a4a5d036e24b7ec7189743b63/controllers/users.js#L59) is giving back some issues. It looks like you're searching for the user by an ID in req.body.id , but comes back as undefined. You're only passing up the `strainId` in the form, but you will also need to pass up the user `id` somehow.

**Comment by romebell** [comment]
### @canourrea23 What are trying to do here?
<img width="644" alt="Screen Shot 2020-12-03 at 7 46 18 AM" src="https://user-images.githubusercontent.com/13144457/101052886-fe41cd80-353b-11eb-9e20-e0a04706b0a7.png">

```js
const express = require("express");
const app = express();
require('dotenv').config()
const cheerio = require('cheerio');
const request = require('request');
//const layouts = require('express-ejs-layouts');
const session = require('express-session');
const passport = require('./config/ppConfig');
const flash = require('connect-flash');
const db = require("./models");
const SECRET_SESSION = process.env.SECRET_SESSION;
console.log('SECRET_SESSION', SECRET_SESSION);
​
app.set('view engine', 'ejs');
​
app.use(require('morgan')('dev'));
app.use(express.urlencoded({ extended: false }));
app.use(express.static(__dirname + '/public'));
//app.use(layouts);
const sessionObject = {
    secret: SECRET_SESSION,
    resave: false,
    saveUninitialized: true
  }
  
app.use(session(sessionObject));
  
  // Initialize passport and run through middleware
app.use(passport.initialize());
app.use(passport.session());
​
// Flash
// Using flash throughout app to send temp messages to user
app.use(flash());
​
// Messages that will be accessible to every view
app.use((req, res, next) => {
// Before every route, we will attach a user to res.local
res.locals.alerts = req.flash();
res.locals.currentUser = req.user;
next();
});
​
app.get('/', (req, res) => {
    console.log(res.locals.alerts);
    res.render('index', { alerts: res.locals.alerts });
  });

let city = Washington;
const city = {
    method: 'GET',
    url: `https://www.numbeo.com/cost-of-living/in/${city}`
}
request(${newLocation}, (err, res, body) => {
    if (err) return console.error(err);
    let $ = cheerio.load(body);
    let title = $('tr').attr('class', 'first_currency');
    let milkPrice = Number($('.first_currency').find('span').text().split('\n')[10].split('$')[0]);
    console.log(milkPrice);
  });
​
const PORT = process.env.PORT || 3000;
​
app.get("/thing", (req, res) => res.send("Connected")); 
​
const server = app.listen(PORT, () => {
  console.log(`You are connected ${PORT} 🎧`);
});
​
module.exports = server;
```

**Comment by sschneeberg** [comment]
<img width="737" alt="Screen Shot 2020-12-03 at 10 54 29 AM" src="https://user-images.githubusercontent.com/73137932/101053632-01e24e00-3556-11eb-8a6b-ef6b28c638b3.png">

Getting syntax error around my range when SQL parses it.  This is the closest I've gotten to making it work because SQL is actually seeing values this time

**Comment by canourrea23** [comment]
> ### @canourrea23 What are trying to do here?
> <img alt="Screen Shot 2020-12-03 at 7 46 18 AM" width="644" src="https://user-images.githubusercontent.com/13144457/101052886-fe41cd80-353b-11eb-9e20-e0a04706b0a7.png">
> 
> ```js
> const express = require("express");
> const app = express();
> require('dotenv').config()
> const cheerio = require('cheerio');
> const request = require('request');
> //const layouts = require('express-ejs-layouts');
> const session = require('express-session');
> const passport = require('./config/ppConfig');
> const flash = require('connect-flash');
> const db = require("./models");
> const SECRET_SESSION = process.env.SECRET_SESSION;
> console.log('SECRET_SESSION', SECRET_SESSION);
> ​
> app.set('view engine', 'ejs');
> ​
> app.use(require('morgan')('dev'));
> app.use(express.urlencoded({ extended: false }));
> app.use(express.static(__dirname + '/public'));
> //app.use(layouts);
> const sessionObject = {
>     secret: SECRET_SESSION,
>     resave: false,
>     saveUninitialized: true
>   }
>   
> app.use(session(sessionObject));
>   
>   // Initialize passport and run through middleware
> app.use(passport.initialize());
> app.use(passport.session());
> ​
> // Flash
> // Using flash throughout app to send temp messages to user
> app.use(flash());
> ​
> // Messages that will be accessible to every view
> app.use((req, res, next) => {
> // Before every route, we will attach a user to res.local
> res.locals.alerts = req.flash();
> res.locals.currentUser = req.user;
> next();
> });
> ​
> app.get('/', (req, res) => {
>     console.log(res.locals.alerts);
>     res.render('index', { alerts: res.locals.alerts });
>   });
> 
> let city = Washington;
> const city = {
>     method: 'GET',
>     url: `https://www.numbeo.com/cost-of-living/in/${city}`
> }
> request(${newLocation}, (err, res, body) => {
>     if (err) return console.error(err);
>     let $ = cheerio.load(body);
>     let title = $('tr').attr('class', 'first_currency');
>     let milkPrice = Number($('.first_currency').find('span').text().split('\n')[10].split('$')[0]);
>     console.log(milkPrice);
>   });
> ​
> const PORT = process.env.PORT || 3000;
> ​
> app.get("/thing", (req, res) => res.send("Connected")); 
> ​
> const server = app.listen(PORT, () => {
>   console.log(`You are connected ${PORT} 🎧`);
> });
> ​
> module.exports = server;
> ```

I am trying to have the interpolation populate with the city I want it to use, but when I use {city} is says its already defined.
![image](https://user-images.githubusercontent.com/73137943/101053697-17f00e80-3556-11eb-8b32-396bc918557a.png)
### Error
```
➜  dev_jobs_usa git:(main) ✗ node index.js
/Users/carolinaurrea/Desktop/SEI1019/unit_two/deliverable/dev_jobs_usa/index.js:58
  const {city} = {
         ^

SyntaxError: Identifier 'city' has already been declared
```

**Comment by romebell** [comment]
@canourrea23 you have city declared `2` times.

You can do this instead:
```js
let city = Washington;
const requestObject = {
    method: 'GET',
    url: `https://www.numbeo.com/cost-of-living/in/${city}`
}
request(requestObject, (err, res, body) => {
    if (err) return console.error(err);
    let $ = cheerio.load(body);
    let title = $('tr').attr('class', 'first_currency');
    let milkPrice = Number($('.first_currency').find('span').text().split('\n')[10].split('$')[0]);
    console.log(milkPrice);
  });
```

### Updated with where `city` and `requestObject` will go
<img width="694" alt="Screen Shot 2020-12-03 at 8 04 22 AM" src="https://user-images.githubusercontent.com/13144457/101055130-832de680-353e-11eb-8325-e0b3f8631c4b.png">

**Comment by fmuwanguzi** [comment]
@romebell 
I keep on getting a `SequelizeDatabaseError: column "userId" does not exist` when I try to post into my users profile. I have checked my associations. i'm not sure if I should try adding a joined table or maybe userWeather with attribute userid and weatherid. 

This is the post route I am trying to use  and the associations below it

```javascript
router.post('/save',(req, res) => { 
    console.log('-----inside of post route for weather-----');
    //Gets form data and add a new record to DB then redirect to my profile page
    console.log('---THE OBJECT MY WEATHER---', req.body);
    db.weather.findOrCreate({
        where: { weather: req.body.city},
            defaults:{
                //icon: req.body.icon,
                country: req.body.country,
                description: req.body.description,
                //main: req.body.main,
                temperature: req.body.temperature,
                feels_like: req.body.feels,
                min_temp: req.body.min,
                max_temp: req.body.max,
                humidity: req.body.humidity}
        }) .then(()=>{
                res.redirect('/profile');
              });
  })
```

### @fmuwanguzi Are both of these inside of 1 model?
❓ ❓ ❓ 
```javascript
   static associate(models) {
      // define association here
      models.weather.belongsTo(models.user)
    }

    static associate(models) {
      // define association here
      models.user.hasMany(models.weather)
    }
```

**Comment by romebell** [comment]
@fmuwanguzi Are both of these inside of 1 model?

<img width="497" alt="Screen Shot 2020-12-03 at 9 28 56 AM" src="https://user-images.githubusercontent.com/13144457/101065406-fab54300-3549-11eb-8467-f9a580fa9392.png">

**Comment by fmuwanguzi** [comment]
@romebell They are in 2 different models. The top one is in my weather model and the bottom one is in my user model. 

@fmuwanguzi What does your model look like for each? Put them here...

**Comment by fmuwanguzi** [comment]
> @romebell They are in 2 different models. The top one is in my weather model and the bottom one is in my user model.
> 
> @fmuwanguzi What does your model look like for each? Put them here...

@romebell please see below
####Weather
```javascript
    static associate(models) {
      // define association here
      models.weather.belongsTo(models.user)
    }
  };
  weather.init({
    city: DataTypes.STRING,
    country: DataTypes.STRING,
    description: DataTypes.STRING,
    temperature: DataTypes.FLOAT,
    feels_like: DataTypes.FLOAT,
    min_temp: DataTypes.FLOAT,
    max_temp: DataTypes.FLOAT,
    humidity: DataTypes.INTEGER
  }, {
    sequelize,
    modelName: 'weather',
  });
  return weather;
};
```
####user
```javascript
    static associate(models) {
      // define association here
      models.user.hasMany(models.weather)
    }
  };
  user.init({
    name: {
      type: DataTypes.STRING,
      validate: {
        len: {
          args: [1,99],
          msg: 'Name must be between 1 and 99 characters'
        }
      }
    },
    email: {
      type: DataTypes.STRING,
      validate: {
        isEmail: {
          msg: 'Invalid email'
        }
      }
    },
    password: {
      type: DataTypes.STRING,
      validate: {
        len: {
          args: [8,99],
          msg: 'Password must be between 8 and 99 characters'
        }
      }
    }
  }, {
    sequelize,
    modelName: 'user',
  });

  user.addHook('beforeCreate', function(pendingUser) {
    // Bcrypt hash a password for us
    let hash = bcrypt.hashSync(pendingUser.password, 12);
    // Set password to equal the hash
    pendingUser.password = hash;
    console.log(pendingUser);
  });
  
  user.prototype.validPassword = function(passwordTyped) {
    let correctPassword = bcrypt.compareSync(passwordTyped, this.password);
    console.log('Inside of validPassword', correctPassword);
    // return true or false based on correct password or not
    return correctPassword;
  }
  
  // Remove the password before it gets serialized 
  user.prototype.toJSON = function() {
    console.log('Inside of the toJSON method');
    let userData = this.get();
    delete userData.password;
    console.log(userData);
    return userData;
  }

  return user;
};
```

**Comment by romebell** [comment]
@marjames98 go to my [express_authentication](https://github.com/romebell/express_authentication) repo and use that as a template. From there you will do the following:

### Step 1: Use my template
<img width="1436" alt="Screen Shot 2020-12-03 at 9 46 24 AM" src="https://user-images.githubusercontent.com/13144457/101068080-284fbb80-354d-11eb-89b1-578e1ddd0dfa.png">

### Step 2: Add `what_to_cook` 
<img width="1297" alt="Screen Shot 2020-12-03 at 9 48 37 AM" src="https://user-images.githubusercontent.com/13144457/101068347-7664bf00-354d-11eb-80a2-3d2be3212f76.png">

### Step 3: Add @romebell as a `collaborator`

<img width="923" alt="Screen Shot 2020-12-03 at 9 49 36 AM" src="https://user-images.githubusercontent.com/13144457/101068453-9ac09b80-354d-11eb-94f1-00c7797ebc9f.png">
---
<img width="1104" alt="Screen Shot 2020-12-03 at 9 49 58 AM" src="https://user-images.githubusercontent.com/13144457/101068507-a90eb780-354d-11eb-9214-17b3f04e7678.png">
---
<img width="1190" alt="Screen Shot 2020-12-03 at 9 50 25 AM" src="https://user-images.githubusercontent.com/13144457/101068543-b330b600-354d-11eb-8e17-87a9416cdefb.png">

### Step 4: Clone `what_to_cook` to your local machine

### Step 5: Install the node packages
```text
npm install
```

### Step 6: Change the name of the database inside of `config.json` file
```json

{
  "development": {
    "database": "what_to_cook_development",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "test": {
    "database": "what_to_cook_test",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "production": {
    "database": "what_to_cook_production",
    "host": "127.0.0.1",
    "dialect": "postgres"
  }
}
```

### Step 7: Create `database` called `what_to_cook_development` inside of your terminal
```text
Put the command here... You can edit this message.
```

**Comment by romebell** [comment]
@canourrea23 
So i am thinking of doing something like this to get the city I want to populate. Am I on the right track?
---
❓
1. How can we make this similar to what we want to build out? 
2. Is this where you're putting the scraping data?
---
```js
router.get('/:id', (req,res) => {
  const id = req.params.id
  axios.get(`https://pokeapi.co/api/v2/pokemon/${id}/`)
  .then(response => {
    let pokemon = response.data;
    console.log(pokemon)
    {res.render('pokemon/show', { pokemon })}
})
```

### `profile.ejs`
```ejs
<ol>
    <% const newLocation => { %>
        <li>Washington: <% Washington %></li>
        <li>New York: <% New-York %> </li>
        <li>Los Angeles: <% Los-Angeles %></li>
        <li>San Francisco: <% San-Francisco %></li>
        <li>Seattle: <% Seattle %></li>
        <li>Los-Angeles: <% Los-Angeles %></li>
        <li>Chicago: <% Chicago %></li>
        <li>Baltimore: <% Baltimore %> </li>
        <li>Atlanta: <% 'Atlanta %> </li>
        <li>Dallas: <% 'Dallas' %> </li>
        <li>Austin: <% 'Austin' %> </li>
    <% } %> 
</ol>
```

**Comment by maddevred** [comment]
@romebell 
![Screenshot from 2020-12-03 13-10-21](https://user-images.githubusercontent.com/73178321/101070355-3e6b7500-3569-11eb-8db4-cecc8b81ccf0.png) step 7

**Comment by canourrea23** [comment]
> ## @canourrea23
> So i am thinking of doing something like this to get the city I want to populate. Am I on the right track?
> ❓
> 
> 1. How can we make this similar to what we want to build out?
> 2. Is this where you're putting the scraping data?
### response
> 1. It's similar in that we are grabbing the name and inputting it to the end point.
> 2. I want you to see the list of cities in your profile and click on the one you are interested in, get that information back and hopefully to be able to save that data if you choose to.
> ```js
> router.get('/:id', (req,res) => {
>   const id = req.params.id
>   axios.get(`https://pokeapi.co/api/v2/pokemon/${id}/`)
>   .then(response => {
>     let pokemon = response.data;
>     console.log(pokemon)
>     {res.render('pokemon/show', { pokemon })}
> })
> ```
> 
> ### `profile.ejs`
> ```
> <ol>
>     <% const newLocation => { %>
>         <li>Washington: <% Washington %></li>
>         <li>New York: <% New-York %> </li>
>         <li>Los Angeles: <% Los-Angeles %></li>
>         <li>San Francisco: <% San-Francisco %></li>
>         <li>Seattle: <% Seattle %></li>
>         <li>Los-Angeles: <% Los-Angeles %></li>
>         <li>Chicago: <% Chicago %></li>
>         <li>Baltimore: <% Baltimore %> </li>
>         <li>Atlanta: <% 'Atlanta %> </li>
>         <li>Dallas: <% 'Dallas' %> </li>
>         <li>Austin: <% 'Austin' %> </li>
>     <% } %> 
> </ol>
> ```

**Comment by romebell** [comment]
```js
app.get('/:city', async (req, res) => {
    const city = req.params.city[0].toUpperCase() + req.params.city.slice(1).toLowerCase();
    const { currency = 'CAD' } = req.query;
    const response = await fetch(`https://www.numbeo.com/cost-of-living/in/${city}?displayCurrency=${currency}`);
    if (!response.ok) {
        return res.status(response.status).send(response.statusText);
    }
    const html = await response.text();
    const $ = cheerio.load(html);
    const rows = $('body > div.innerWidth > table > tbody > tr')
        .filter((i, el) => $(el).children('td').length === 3)
        .map((i, el) => $(el).children()
        .map((i, el) => $(el).text().trim()).toArray())
        .toArray();
});
```

**Comment by romebell** [comment]
@canourrea23 
```js
app.get('/:city', async (req, res) => {
    const city = req.params.city[0].toUpperCase() + req.params.city.slice(1).toLowerCase();
    console.log('CITY',city);
    // const { currency = 'CAD' } = req.query;
    console.log(req.query);
    fetch(`https://www.numbeo.com/cost-of-living/in/${city}`, (error, meta, body) => {
      let html = body.toString();
      const $ = cheerio.load(html);

      const priceRows = $('body > div.innerWidth > table.data_wide_table.new_bar_table > tbody > tr > td.priceValue > span.first_currency').text().split(' ');
      console.log(priceRows);

    })
});
```

**Comment by fmuwanguzi** [comment]
@romebell 
![Screen Shot 2020-12-04 at 4 05 38 PM](https://user-images.githubusercontent.com/72531389/101214779-91692900-364a-11eb-90e4-866a5d92152d.png)

Every-time I try to create on my post route  it updates the database but all the values of the object come out as null

```javascript 
router.post('/save', isLoggedIn, (req, res) => { 
    console.log('-----inside of post route for weather-----');
    //Gets form data and add a new record to DB then redirect to my profile page
    console.log('---THE OBJECT MY WEATHER---', req.body); //shows object
    console.log(req.user.id, '----USER ID---') / shows user
    db.weather.create({
        where: { weather: req.body.city,
            //id: req.body.id,
            //icon: req.body.icon,
            country: req.body.country,
            description: req.body.description,
            //main: req.body.main,
            temperature: req.body.temperature,
            feels_like: req.body.feels,
            min_temp: req.body.min,
            max_temp: req.body.max,
            humidity: req.body.humidity}
        }) 
        .then((weather)=>{
            console.log(weather.get()); //results are coming back as null
            res.redirect('/profile');
        });
  })
```
I just see a [object:null prototype] when I console.log(req.body);
![Screen Shot 2020-12-04 at 4 27 08 PM](https://user-images.githubusercontent.com/72531389/101216478-94194d80-364d-11eb-91ba-b4da872d352d.png)

**Comment by romebell** [comment]
@canourrea23 `parsedPriceRows`

```js
app.get('/:city', async (req, res) => {
  const city = req.params.city[0].toUpperCase() + req.params.city.slice(1).toLowerCase();
  console.log('CITY',city);
  // const { currency = 'CAD' } = req.query;
  console.log(req.query);
  fetch(`https://www.numbeo.com/cost-of-living/in/${city}`, (error, meta, body) => {
    let html = body.toString();
    const $ = cheerio.load(html);

    const priceRows = String($('body > div.innerWidth > table.data_wide_table.new_bar_table > tbody > tr > td.priceValue > span.first_currency').text().split(' ')[0]).split('$');
    console.log(priceRows);

    const parsedPriceRows = priceRows.map(element => {
      if (element.includes(',')) {
        let newPrice = Math.round(Number(element.replace(',', '')));
        return newPrice;
      } else {
        let newPrice = Math.round(Number(element));
        return newPrice;
      }
    });

    console.log(parsedPriceRows[9])

    const locationObject = { 
      bedroom_in_city: '',
      bedroom_outside_centre: '',
      public_transit: '',
      internet: '',
      childcare: '',
      gas: '',
      average_meal: '',
      milk: '',
      utilities: '',
    }
  });
```

**Comment by romebell** [comment]
```js
const postArray = posts.map(post => {
  return post.get();
})
console.log(postArray);
```

**Comment by romebell** [comment]
All you need to do is install the `axios` library by saying:

```text
npm i axios
```

From there inside of your `server.js` file, you will need to require `axios` at the top of your file:
```js
const axios = require('axios');
```

Inside of your route, you can do:

```js
axios.get('<endpoint>')
.then(response => {
     console.log(response.data);
});
```

**Comment by romebell** [comment]
```js
app.get('/:city', async (req, res) => {
  const city = req.params.city[0].toUpperCase() + req.params.city.slice(1).toLowerCase();
  console.log('CITY',city);
  // const { currency = 'CAD' } = req.query;
  console.log(req.query);
  fetch(`https://www.numbeo.com/cost-of-living/in/${city}`, (error, meta, body) => {
    let html = body.toString();
    const $ = cheerio.load(html);
​
    const priceRows = String($('body > div.innerWidth > table.data_wide_table.new_bar_table > tbody > tr > td.priceValue > span.first_currency').text().split(' ')[0]).split('$');
    console.log(priceRows);
​
    const parsedPriceRows = priceRows.map(element => {
      if (element.includes(',')) {
        let newPrice = Math.round(Number(element.replace(',', '')));
        return newPrice;
      } else {
        let newPrice = Math.round(Number(element));
        return newPrice;
      }
    });
​
    console.log(parsedPriceRows[48])
​
    const locationObject = { 
      bedroom_in_city: parsedPriceRows[47],
      bedroom_outside_centre: parsedPriceRows[48],
      public_transit: parsedPriceRows[28],
      internet: parsedPriceRows[37],
      childcare: parsedPriceRows[41],
      gas: (parsedPriceRows[32]*3.785),
      average_meal: parsedPriceRows[0],
      milk: (parsedPriceRows[8]*3.785),
      utilities: parsedPriceRows[35],
    }
  db.location.create(locationObject)
  .then((newLocation) => {
    console.log(newLocation.get());
    
    res.render('city', { city, newLocation });  
  });
});
```

**Comment by romebell** [comment]
## Scratch paper
```ejs
<!-- <ol> -->
    <!-- <li>Bedroom In City: <%= location.bedroom_in_city %></li> -->
<!-- </ol> -->

<!-- <li>New York: <% New-York %> </li>
<li>Los Angeles: <% Los-Angeles %></li>
<li>San Francisco: <% San-Francisco %></li>
<li>Seattle: <% Seattle %></li>
<li>Los-Angeles: <% Los-Angeles %></li>
<li>Chicago: <% Chicago %></li>
<li>Baltimore: <% Baltimore %> </li>
<li>Atlanta: <% 'Atlanta %> </li>
<li>Dallas: <% 'Dallas' %> </li>
<li>Austin: <% 'Austin' %> </li> -->
```

**Comment by romebell** [comment]
@canourrea23 
```js
app.get('/:city', async (req, res) => {
  const city = req.params.city[0].toUpperCase() + req.params.city.slice(1).toLowerCase();
  
  fetch(`https://www.numbeo.com/cost-of-living/in/${city}`, (error, meta, body) => {
    let html = body.toString();
    const $ = cheerio.load(html);
    const priceRows = String($('body > div.innerWidth > table.data_wide_table.new_bar_table > tbody > tr > td.priceValue > span.first_currency').text().split(' ')[0]).split('$');
    const parsedPriceRows = priceRows.map(element => {
      if (element.includes(',')) {
        let newPrice = Math.round(Number(element.replace(',', '')));
        return newPrice;
      } else {
        let newPrice = Math.round(Number(element));
        return newPrice;
      }
    });

    const locationObject = { 
      bedroom_in_city: parsedPriceRows[47],
      bedroom_outside_centre: parsedPriceRows[48],
      public_transit: parsedPriceRows[28],
      internet: parsedPriceRows[37],
      childcare: parsedPriceRows[41],
      gas: (Math.round(parsedPriceRows[32]*3.785)),
      average_meal: parsedPriceRows[0],
      milk: (Math.round(parsedPriceRows[8]*3.785)),
      utilities: parsedPriceRows[35],
    }
    db.location.create(locationObject)
    .then(newLocation => {
      console.log(newLocation.get());
      // Carolina, make sure that you're getting back the new location before you send
      // it to the ejs page.
      res.render('city');
    });
  });
});
```

**Comment by romebell** [comment]
@fmuwanguzi You need to send the `weather` up to the `profile` page
```js
.then((weather) => {
   console.log(weather.get());
   res.redirect('/profile', { weather: weather.get() });
});
```

Inside of your `ejs` page, you can do the following:

```ejs
<h3>Your places</h3>
<p><%= weather.city %></p>
<p><%= weather.description %></p>
<p><%= weather.temperature %></p>
<p><%= weather.feels_like %></p>
<p><%= weather.min_temp %></p>
<p><%= weather.max_temp %></p>
<p><%= weather.humidity %></p>
```

**Comment by romebell** [comment]
@canourrea23 Can you update your first couple lines to this....
```js
// Modules 
require('dotenv').config();
const express = require("express");
const cheerio = require('cheerio');
const request = require('request');
const layouts = require('express-ejs-layouts');
const session = require('express-session');
const passport = require('./config/ppConfig');
const flash = require('connect-flash');
const fetch = require('fetch').fetchUrl;
const db = require("./models");
const SECRET_SESSION = process.env.SECRET_SESSION;

const app = express();
const isLoggedIn = require('./middleware/isLoggedIn');
```

**Comment by fmuwanguzi** [comment]
> @fmuwanguzi You need to send the `weather` up to the `profile` page
> 
> ```js
> .then((weather) => {
>    console.log(weather.get());
>    res.redirect('/profile', { weather: weather.get() });
> });
> ```
> 
> Inside of your `ejs` page, you can do the following:
> 
> ```
> <h3>Your places</h3>
> <p><%= weather.city %></p>
> <p><%= weather.description %></p>
> <p><%= weather.temperature %></p>
> <p><%= weather.feels_like %></p>
> <p><%= weather.min_temp %></p>
> <p><%= weather.max_temp %></p>
> <p><%= weather.humidity %></p>
> ```

@romebell so it renders it to another page weather/save. I am in the process of trying to to see what is being rendered so I can use findAll to display more than one place(added to saved) using a get route. It comes back mostly empty it does however show the user 

![Screen Shot 2020-12-05 at 1 22 36 PM](https://user-images.githubusercontent.com/72531389/101260305-f67d5700-36fc-11eb-9275-37ba3be6f299.png)
![Screen Shot 2020-12-05 at 1 23 11 PM](https://user-images.githubusercontent.com/72531389/101260317-0a28bd80-36fd-11eb-9598-41ad4e6dc06b.png)

Actually i figured this part out I know just need to have what I'm printing display correctly

**Comment by AlexJBustillos** [comment]
https://github.com/AlexJBustillos/Loud-and-Green/issues/2
