### ISSUE TITLE
Friday, November 13, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#2]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by codebypaul** [comment]
### Challenge 1
```JavaScript
function moreDotLessDash(str) {
    myArray = str.split('')
    let dots = 0
    let dashes = 0
    for (let i = 0; i < myArray.length; i++){
        if (myArray[i] === '.'){
            dots++
        }else if (myArray[i] === '-'){
            dashes++
        }else{
            null
        }
    }
    if (dots > dashes){
        console.log(true);
    }else{
        console.log(false);
    }
}
```
### Challenge 2
```JavaScript
function opposingSums(array) {
    const newArray = []
    while (array.length > (array.length/2)){
        newArray.push(array[0] + array[array.length -1])
        array.pop()
        array.shift()
    }
    console.log(newArray);   
}
```

**Comment by marjames98** [comment]
![Screenshot from 2020-11-13 10-37-54](https://user-images.githubusercontent.com/73178321/99090356-81ef4680-259c-11eb-8548-d863bf71fce2.png)

**Comment by maddevred** [comment]
@romebell 
![Screenshot from 2020-11-13 10-40-15](https://user-images.githubusercontent.com/73178321/99090421-a1866f00-259c-11eb-805d-8850cfc05391.png)

**Comment by Swolepenguin** [comment]
Ashton

**Comment by lev-choubine** [comment]
Lev

**Comment by CoreyWilson319** [comment]
Corey

**Comment by lev-choubine** [comment]
I am all caught up now. I am good thanks.

**Comment by fmuwanguzi** [comment]
`
testdb=# CREATE TABLE students (
testdb(# id SERIAL PRIMARY KEY,
testdb(# name TEXT,
testdb(# phone VARCHAR(15),
testdb(# email TEXT,
testdb(# );
ERROR:  syntax error at or near ")"
LINE 6: );
        ^
testdb=#
`

**Comment by fmuwanguzi** [comment]
![Screen Shot 2020-11-13 at 11 08 05 AM](https://user-images.githubusercontent.com/72531389/99093471-8289dc00-25a0-11eb-9578-50be6dc6b21d.png)

**Comment by canourrea23** [comment]
I didn't add the VALUES before closing 
```
carolinaurrea=# \connect testdb;
You are now connected to database "testdb" as user "carolinaurrea".
testdb=# CREATE TABLE students (
testdb(# id SERIAL PRIMARY KEY,
testdb(# name TEXT
testdb(# );
CREATE TABLE
testdb=# INSERT INTO students
testdb-# (name, phone, email)
testdb-# VALUES
testdb-# ('William', '(415)777-8888', 'william@ga.co');
ERROR:  column "phone" of relation "students" does not exist
LINE 2: (name, phone, email)
```

**Comment by tcgilbert** [comment]
![Screen Shot 2020-11-13 at 11 19 27 AM](https://user-images.githubusercontent.com/64277654/99094926-76068300-25a2-11eb-97cd-06f3ee5da354.png)

**Comment by pmacaluso3** [comment]
Carolina, you have a few options. You can drop the students table and recreate it including the phone column. You can also use a command like this which we're not officially covering this morning, but it's good to know:
```sql
ALTER TABLE students ADD phone text
```
There is documentation for it here: https://www.w3schools.com/sql/sql_alter.asp

**Comment by canourrea23** [comment]
Was able to Drop and restart the process.

**Comment by jtreeves** [comment]
![Screen Shot 2020-11-13 at 12 21 40 PM](https://user-images.githubusercontent.com/15839768/99101638-de596280-25aa-11eb-81a9-d79f5cd12741.png)

```javascript
const express = require('express')
const app = express()

app.get('/', function(req, res) {
    res.send('Hello, world!')
})

app.listen(8000)
```

**Comment by maddevred** [comment]
@romebell 
![Screenshot from 2020-11-13 12-47-02](https://user-images.githubusercontent.com/73178321/99103988-5ecd9280-25ae-11eb-99db-fda085d9c0a9.png)

**Comment by mkzarra** [comment]
> @romebell
> ![Screenshot from 2020-11-13 12-47-02](https://user-images.githubusercontent.com/73178321/99103988-5ecd9280-25ae-11eb-99db-fda085d9c0a9.png)

remove the `function` keyword when using `=>`. They're just different ways to write a function. Either will work here, but they can't be combined.


```js
app.get('/blog', (req, res) => {
    res.send('Welcome to my blog');
});
```

**Comment by canourrea23** [comment]
I am getting this error when I try to run nodemon index.js on an other terminal
![Screen Shot 2020-11-13 at 3 41 41 PM](https://user-images.githubusercontent.com/73137943/99119149-cb548b80-25c6-11eb-9715-00a6c3d2a920.png)

**Comment by romebell** [comment]
@canourrea23 You have a server already running.

**Comment by canourrea23** [comment]
```
app.get('/blog/:date', (req, res) => {
    res.render('blog', { date: req.params.date })
});
```
![Screen Shot 2020-11-13 at 4 42 00 PM](https://user-images.githubusercontent.com/73137943/99123924-2d18f380-25cf-11eb-92bc-8786782fd2a0.png)
