### ISSUE TITLE
Dexter's Pod

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#21]
### Add your link to the ISSUE that you create here. Be sure to assign your Pod Leader

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-11-30 at 3 36 35 PM](https://user-images.githubusercontent.com/71084561/100668624-d840e100-3321-11eb-8366-b4a085360e8e.png)
When i am using the api key that used as a sample i am able to see the data i am looking for but when i try using my api key i don't get the data im looking for.
https://developer.climacell.co/v3/reference

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-12-01 at 9 02 27 AM](https://user-images.githubusercontent.com/71084561/100757394-f22b0400-33b3-11eb-9be1-8c10d088b610.png)
![Screen Shot 2020-12-01 at 9 02 48 AM](https://user-images.githubusercontent.com/71084561/100757432-fd7e2f80-33b3-11eb-9fff-d76e8c9edd3d.png)
![Screen Shot 2020-12-01 at 9 03 30 AM](https://user-images.githubusercontent.com/71084561/100757524-171f7700-33b4-11eb-80e5-bcbc774d18d7.png)
I am trying to render my api data onto my ejs page but it is saying air is not defined.

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-12-01 at 10 43 16 AM](https://user-images.githubusercontent.com/71084561/100769695-070e9400-33c2-11eb-8da8-8f16ece294bf.png)
I cant get the data to display in the console, the api works when i run it in postman.

**Comment by dextermichael** [comment]
you have " `console.log(response.data.aqi)`  
- shouldnt it be api?

**Comment by JaxonNarramore** [comment]
<img width="1349" alt="Screen Shot 2020-12-03 at 9 07 33 AM" src="https://user-images.githubusercontent.com/71084561/101046895-fcc9d280-3546-11eb-9f6e-9433afffc245.png">
![Screen Shot 2020-12-03 at 9 08 00 AM](https://user-images.githubusercontent.com/71084561/101046946-0bb08500-3547-11eb-8153-7f54de2f5ade.png)
![Screen Shot 2020-12-03 at 9 08 28 AM](https://user-images.githubusercontent.com/71084561/101047013-1cf99180-3547-11eb-8da7-fc043632572c.png)
I am trying to add the cities to the users profile but trying to add them i get this message and me nor the TA could figure it out last night.

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-12-03 at 9 08 00 AM](https://user-images.githubusercontent.com/71084561/101046946-0bb08500-3547-11eb-8153-7f54de2f5ade.png)

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-12-03 at 9 08 28 AM](https://user-images.githubusercontent.com/71084561/101047013-1cf99180-3547-11eb-8da7-fc043632572c.png)

For some reason the images didnt show up when i posed the links to my issue above so here they are.

**Comment by jtreeves** [comment]
https://github.com/jtreeves/read-this-next/issues/2
