### ISSUE TITLE
Heroku Deployment Issues

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#23]
Post all of your issues here with a `screenshot`

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-12-03 at 2 13 39 PM](https://user-images.githubusercontent.com/71084561/101082855-c3f32300-3571-11eb-9d7a-621a9c8cd7a3.png)
✅

**Comment by fmuwanguzi** [comment]
![Screen Shot 2020-12-03 at 3 13 47 PM](https://user-images.githubusercontent.com/72531389/101082869-2c460280-357a-11eb-80d3-37c939ad1e32.png)
✅

**Comment by canourrea23** [comment]
`➜  dev_jobs_usa git:(main) ✗ npm -g audit fix
npm ERR! code EAUDITGLOBAL
npm ERR! `npm audit` does not support testing globals

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carolinaurrea/.npm/_logs/2020-12-03T20_19_28_015Z-debug.log
➜  dev_jobs_usa git:(main) ✗ heroku --version
heroku/7.47.4 darwin-x64 node-v14.15.0
➜  dev_jobs_usa git:(main) ✗ npm ls -g | grep heroku
├─┬ heroku@7.47.4
│ ├─┬ @heroku-cli/color@1.1.14
│ ├─┬ @heroku-cli/command@8.4.0
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├─┬ heroku-client@3.1.0
│ ├─┬ @heroku-cli/plugin-addons-v5@7.42.2
│ │ ├─┬ heroku-cli-util@8.0.12
│ │ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ │ ├── heroku-client@3.1.0 deduped
│ ├─┬ @heroku-cli/plugin-apps@7.47.0
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ │ ├── @heroku-cli/schema@1.0.25
│ ├─┬ @heroku-cli/plugin-apps-v5@7.43.0
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ │ ├── heroku-cli-util@8.0.12 deduped
│ ├─┬ @heroku-cli/plugin-auth@7.47.4
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ ├─┬ @heroku-cli/plugin-autocomplete@7.43.0
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ ├─┬ @heroku-cli/plugin-buildpacks@7.43.0
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ │ ├─┬ @heroku/buildpack-registry@1.0.1
│ │ ├── heroku-cli-util@8.0.12 deduped
│ ├─┬ @heroku-cli/plugin-certs@7.43.0
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ ├─┬ @heroku-cli/plugin-certs-v5@7.47.0
│ │ ├── heroku-cli-util@8.0.12 deduped
│ ├─┬ @heroku-cli/plugin-ci@7.43.0
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ ├─┬ @heroku-cli/plugin-ci-v5@7.43.0
│ │ ├── @heroku-cli/command@8.4.0 deduped
│ │ ├─┬ @heroku-cli/plugin-run-v5@7.43.0
│ │ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ │ ├── @heroku-cli/command@8.4.0 deduped
│ │ │ ├── @heroku-cli/notifications@1.2.2 deduped
│ │ │ ├── @heroku/eventsource@1.0.7 deduped
│ │ │ ├── heroku-cli-util@8.0.12 deduped
npm│ │ ├── heroku-cli-util@8.0.12 deduped
│ ├─┬ @heroku-cli/plugin-config@7.43.0
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├── @heroku-cli/command@8.4.0 deduped
 ERR!│ ├─┬ @heroku-cli/plugin-container-registry-v5@7.42.12
 missing: @babel/code-frame@^7.0.0, required by eslint@6.7.2
npm │ │ ├── heroku-cli-util@8.0.12 deduped
ERR! missing: eslint-scope@^5.0.0, required by eslint@6.7.2
│ ├─┬ @heroku-cli/plugin-git@7.43.0
npm│ │ ├── @heroku-cli/color@1.1.14 deduped
 │ │ ├── @heroku-cli/command@8.4.0 deduped
ERR! missing: eslint-visitor-keys@^1.1.0, required by eslint@6.7.2
│ ├─┬ @heroku-cli/plugin-local@7.43.0
npm│ │ ├── @heroku-cli/command@8.4.0 deduped
 ERR! missing: espree@^6.1.2, required by eslint@6.7.2
│ ├─┬ @heroku-cli/plugin-oauth-v5@7.42.12
npm │ │ ├── heroku-cli-util@8.0.12 deduped
ERR!│ ├─┬ @heroku-cli/plugin-orgs-v5@7.43.0
│ │ ├── @heroku-cli/command@8.4.0 deduped
 missing: esquery@^1.0.1, required by eslint@6.7.2
│ │ ├── heroku-cli-util@8.0.12 deduped
npm ERR! missing: esutils@^2.0.2, required by eslint@6.7.2
npm ERR!│ ├─┬ @heroku-cli/plugin-pg-v5@7.47.4
│ │ ├─┬ @heroku-cli/plugin-addons@1.2.31
 missing: functional-red-black-tree@^1.0.1, required by eslint@6.7.2
│ │ │ ├── heroku-cli-util@8.0.12 deduped
npm │ │ ├── heroku-cli-util@8.0.12 deduped
ERR! missing: ignore@^4.0.6, required by eslint@6.7.2
npm ERR! missing: import-fresh@^3.0.0, required by eslint@6.7.2
npm │ ├─┬ @heroku-cli/plugin-pipelines@7.47.2
│ │ ├── @heroku-cli/color@1.1.14 deduped
│ │ ├── @heroku-cli/command@8.4.0 deduped
ERR!│ │ ├── @heroku-cli/schema@1.0.25 deduped
 missing: imurmurhash@^0.1.4, required by eslint@6.7.2
npm ERR! missing: json-stable-stringify-without-jsonify@^1.0.1, required by eslint@6.7.2
npm ERR! missing: levn@^0.3.0, required by eslint@6.7.2
npm ERR! missing: natural-compare@^1.4.0, required by eslint@6.7.2
npm ERR! missing: progress@^2.0.0, required by eslint@6.7.2
npm ERR! missing: regexpp@^2.0.1, required by eslint@6.7.2
npm ERR! missing: table@^5.2.3, required by eslint@6.7.2
npm ERR! missing: text-table@^0.2.0, required by eslint@6.7.2
npm ERR! missing: v8-compile-cache@^2.0.3, required by eslint@6.7.2
npm ERR! missing: fast-deep-equal@^2.0.1, required by ajv@6.10.2
npm ERR! missing: fast-json-stable-stringify@^2.0.0, required by ajv@6.10.2
npm ERR! missing: json-schema-traverse@^0.4.1, required by ajv@6.10.2
npm ERR! missing: uri-js@^4.2.2, required by ajv@6.10.2
npm ERR!│ │ ├── heroku-cli-util@8.0.12 deduped
 missing: esutils@^2.0.2, required by doctrine@3.0.0
│ ├─┬ @heroku-cli/plugin-ps@7.43.0
npm│ │ ├── @heroku-cli/color@1.1.14 deduped
 │ │ ├── @heroku-cli/command@8.4.0 deduped
ERR!│ ├─┬ @heroku-cli/plugin-ps-exec@2.3.8
 missing: eslint-visitor-keys@^1.1.0, required by eslint-utils@1.4.3
│ │ ├── heroku-cli-util@8.0.12 deduped
npm│ │ ├─┬ heroku-exec-util@0.7.5
│ │ │ ├─┬ @heroku/socksv5@0.0.9
 │ │ │ ├── heroku-cli-util@8.0.12 deduped
ERR! missing: flatted@^2.0.0, required by flat-cache@2.0.1
│ ├─┬ @heroku-cli/plugin-redis-v5@7.45.0
npm │ │ ├── heroku-cli-util@8.0.12 deduped
ERR! missing: rimraf@2.6.3, required by flat-cache@2.0.1
npm │ ├─┬ @heroku-cli/plugin-run@7.43.0
ERR!│ │ ├── @heroku-cli/color@1.1.14 deduped
 missing: type-fest@^0.8.1, required by globals@12.3.0
│ │ ├── @heroku-cli/command@8.4.0 deduped
npm │ │ ├─┬ @heroku-cli/notifications@1.2.2
ERR!│ │ ├─┬ @heroku/eventsource@1.0.7
 missing: cli-width@^2.0.0, required by inquirer@7.0.0
npm ERR! missing: emoji-regex@^8.0.0, required by string-width@4.1.0
npm ERR! missing: deep-is@~0.1.3, required by optionator@0.8.3
npm ERR! missing: levn@~0.3.0, required by optionator@0.8.3
npm ERR! missing: prelude-ls@~1.1.2, required by optionator@0.8.3
npm ERR! missing: type-check@~0.3.2, required by optionator@0.8.3
npm ERR! missing: word-wrap@~1.2.3, required by optionator@0.8.3
npm ERR! missing: @babel/code-frame@^7.0.0, required by eslint@6.7.2
npm ERR! missing: eslint-scope@^5.0.0, required by eslint@6.7.2
npm ERR! missing: eslint-visitor-keys@^1.1.0, required by eslint@6.7.2
npm ERR! missing: espree@^6.1.2, required by eslint@6.7.2
│ ├─┬ @heroku-cli/plugin-spaces@7.43.0
npm│ │ ├── @heroku-cli/command@8.4.0 deduped
 │ │ ├── @heroku-cli/notifications@1.2.2 deduped
ERR!│ │ ├── heroku-cli-util@8.0.12 deduped
 missing: esquery@^1.0.1, required by eslint@6.7.2
│ ├─┬ @heroku-cli/plugin-status@7.43.0
npm│ │ ├── @heroku-cli/color@1.1.14 deduped
 │ │ ├── @heroku-cli/command@8.4.0 deduped
ERR! missing: esutils@^2.0.2, required by eslint@6.7.2
│ ├─┬ @heroku-cli/plugin-webhooks@7.43.0
│ │ ├── @heroku-cli/color@1.1.14 deduped
npm│ │ ├── @heroku-cli/command@8.4.0 deduped
 ERR! missing: functional-red-black-tree@^1.0.1, required by eslint@6.7.2
npm ERR! missing: ignore@^4.0.6, required by eslint@6.7.2
npm ERR! missing: import-fresh@^3.0.0, required by eslint@6.7.2
npm ERR! missing: imurmurhash@^0.1.4, required by eslint@6.7.2
npm ERR! missing: json-stable-stringify-without-jsonify@^1.0.1, required by eslint@6.7.2
npm ERR! missing: levn@^0.3.0, required by eslint@6.7.2
npm ERR! missing: natural-compare@^1.4.0, required by eslint@6.7.2
npm ERR! missing: progress@^2.0.0, required by eslint@6.7.2
npm ERR! missing: regexpp@^2.0.1, required by eslint@6.7.2
npm ERR! missing: table@^5.2.3, required by eslint@6.7.2
npm ERR! missing: text-table@^0.2.0, required by eslint@6.7.2
npm ERR! missing: v8-compile-cache@^2.0.3, required by eslint@6.7.2
npm ERR! missing: fast-deep-equal@^2.0.1, required by ajv@6.10.2
npm ERR! missing: fast-json-stable-stringify@^2.0.0, required by ajv@6.10.2
npm ERR! missing: json-schema-traverse@^0.4.1, required by ajv@6.10.2
npm ERR! missing: uri-js@^4.2.2, required by ajv@6.10.2
npm ERR! missing: esutils@^2.0.2, required by doctrine@3.0.0
npm ERR! missing: eslint-visitor-keys@^1.1.0, required by eslint-utils@1.4.3
npm ERR! missing: mimic-fn@^2.1.0, required by onetime@5.1.0
npm ERR! missing: emoji-regex@^8.0.0, required by string-width@4.1.0
npm ERR! missing: flatted@^2.0.0, required by flat-cache@2.0.1
npm ERR! missing: rimraf@2.6.3, required by flat-cache@2.0.1
npm ERR! missing: type-fest@^0.8.1, required by globals@12.3.0
npm ERR! missing: deep-is@~0.1.3, required by optionator@0.8.3
npm ERR! missing: levn@~0.3.0, required by optionator@0.8.3
npm ERR! missing: prelude-ls@~1.1.2, required by optionator@0.8.3
npm ERR! missing: type-check@~0.3.2, required by optionator@0.8.3
npm ERR! missing: word-wrap@~1.2.3, required by optionator@0.8.3
npm ERR! missing: chai@^4.1.2, required by nock@9.6.1
npm ERR! missing: deep-equal@^1.0.0, required by nock@9.6.1
npm ERR! missing: json-stringify-safe@^5.0.1, required by nock@9.6.1
npm ERR! missing: propagate@^1.0.0, required by nock@9.6.1
npm ERR! missing: qs@^6.5.1, required by nock@9.6.1
│ │ ├── @heroku-cli/command@8.4.0 deduped
➜  dev_jobs_usa git:(main) ✗`
✅

**Comment by tylerdance** [comment]
Not getting anything when I check for global install. Is it ok that I'm doing all this at the desktop rather than project folder?

<img width="819" alt="Screen Shot 2020-12-03 at 3 26 40 PM" src="https://user-images.githubusercontent.com/72777766/101084442-f7d34600-357b-11eb-8054-9b10c2ad5da8.png">

**Comment by romebell** [comment]
@tylerdance You now need to `cd` into your project.

**Comment by canourrea23** [comment]
```
remote:          https://devcenter.heroku.com/articles/node-best-practices#only-git-the-important-bits
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        - A module may be missing from 'dependencies' in package.json
remote:          https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to jobs-for-developers.
remote:
To https://git.heroku.com/jobs-for-developers.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/jobs-for-developers.git'
➜  dev_jobs_usa git:(main) ✗
```
