### ISSUE TITLE
Monday, November 16, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#3]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by wjlock** [comment]
I keep getting this error in my terminal:  

```
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by NikkiHmltn** [comment]
<img width="976" alt="Screen Shot 2020-11-16 at 1 31 14 PM" src="https://user-images.githubusercontent.com/65046641/99310650-2af1a780-2810-11eb-9ff0-9546ade5b840.png">
<img width="728" alt="Screen Shot 2020-11-16 at 1 32 36 PM" src="https://user-images.githubusercontent.com/65046641/99310670-32b14c00-2810-11eb-9cf1-960ab2b927f9.png">
<img width="680" alt="Screen Shot 2020-11-16 at 1 32 47 PM" src="https://user-images.githubusercontent.com/65046641/99310685-380e9680-2810-11eb-927b-9d6230839f6d.png">

**Comment by tcgilbert** [comment]
Cannot find favesController, so I assume there is an importing issue

![Screen Shot 2020-11-16 at 4 34 55 PM](https://user-images.githubusercontent.com/64277654/99310971-cfccae80-2829-11eb-8251-30255dfebcd4.png)
![Screen Shot 2020-11-16 at 4 35 12 PM](https://user-images.githubusercontent.com/64277654/99310978-d1967200-2829-11eb-88c6-4d3795a86842.png)

**Comment by tylerdance** [comment]
<img width="518" alt="Screen Shot 2020-11-16 at 6 26 38 PM" src="https://user-images.githubusercontent.com/72777766/99320338-6a80b980-2839-11eb-9380-e44a23cfd644.png">

Unable to load my `index.ejs` in chrome. `ejs` and `express` both successfully installed as dependencies in my `.json`. `index.ejs` is within my views folder. Any ideas?

**Comment by romebell** [comment]
@tylerdance Did you `require` the module `express-ejs-layouts`?

```js
const ejsLayouts = require('express-ejs-layouts');
```
