### ISSUE TITLE
Tuesday, November 17, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#4]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by nitishdayal** [comment]
Unable to convert buffer from `fs.readFileSync` to a JSON object using `JSON.parse`:
![Screen Shot 2020-11-17 at 8 20 57 AM](https://user-images.githubusercontent.com/14283798/99416646-b0339580-28be-11eb-901c-30b757feba87.png)
![Screen Shot 2020-11-17 at 8 21 55 AM](https://user-images.githubusercontent.com/14283798/99416746-c9d4dd00-28be-11eb-859e-7ef6f45671a6.png)

**Comment by romebell** [comment]
@nitishdayal Do you have a `dinosaurs.json` file?

**Comment by nitishdayal** [comment]
I do, but I just looked at it and it's empty. :) So. Simple enough error. I assumed it was already populated with some data; guess I missed the step where we seeded it. Thanks!

**Comment by NikkiHmltn** [comment]
Having some issues trying to get the img url for cryptids to post. Its breaking my code so I commented it out. Any ideas? 

```html

<form action="/cryptids" method="POST">

    <label for="cryptidName">Name</label>
    <input id="cryptidName" type="text" name="name">
    
    <!-- <label for="imgURL">Image URL</label>
    <input id="imgURL" type="text" name="imgURL"> -->

    <input type="submit">
    </form>
```

**Comment by fmuwanguzi** [comment]
![Screen Shot 2020-11-17 at 12 35 34 PM](https://user-images.githubusercontent.com/72531389/99425833-64d6b280-28d1-11eb-9d4f-9e1283a01c57.png)

This came up once i started my crypt controller

**Comment by NikkiHmltn** [comment]
> ![Screen Shot 2020-11-17 at 12 35 34 PM](https://user-images.githubusercontent.com/72531389/99425833-64d6b280-28d1-11eb-9d4f-9e1283a01c57.png)
> 
> This came up once i started my crypt controller

It looks like "expresss" has one to many 's' there! Try that error out?

**Comment by romebell** [comment]
<img width="882" alt="Screen Shot 2020-11-17 at 9 52 21 AM" src="https://user-images.githubusercontent.com/13144457/99427891-ce979200-28ba-11eb-9709-8d55a692d391.png">

@fmuwanguzi Did you get [this](https://github.com/SEI-ATL/UNIT_2/issues/4#issuecomment-729086446) working?

Double check your spelling of `express` inside your `index.js` file

**Comment by fmuwanguzi** [comment]
I fixed that typo and this came up 
![Screen Shot 2020-11-17 at 12 55 58 PM](https://user-images.githubusercontent.com/72531389/99428138-3efedd00-28d4-11eb-852d-abcd6f3ba149.png)

**Comment by NikkiHmltn** [comment]
<img width="607" alt="Screen Shot 2020-11-17 at 1 48 23 PM" src="https://user-images.githubusercontent.com/65046641/99454647-905e9a80-28db-11eb-94c7-12b8567ac66a.png">
<img width="1207" alt="Screen Shot 2020-11-17 at 1 48 32 PM" src="https://user-images.githubusercontent.com/65046641/99454660-96547b80-28db-11eb-9ae7-b0e029bd7648.png">

**Comment by canourrea23** [comment]
![Screen Shot 2020-11-17 at 4 58 42 PM](https://user-images.githubusercontent.com/73137943/99455707-37e8c680-28f6-11eb-8953-5cb9a60700ee.png)

**Comment by mkzarra** [comment]
@canourrea23  check your " in your inputs

**Comment by canourrea23** [comment]
> @canourrea23 check your " in your inputs

Sorry I was able to get it fixed and I deleted it. Thanks!!
