### ISSUE TITLE
Wednesday, November 18, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#5]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by tylerdance** [comment]
<img width="701" alt="Screen Shot 2020-11-18 at 3 31 59 PM" src="https://user-images.githubusercontent.com/72777766/99584674-45b05180-29b3-11eb-82e0-a9262af19206.png">

**Comment by CoreyWilson319** [comment]
![image](https://user-images.githubusercontent.com/72322079/99584838-7abca400-29b3-11eb-8a03-a854deb5a00c.png)

**Comment by pmacaluso3** [comment]
Corey, on linux you will have to put your username and password into your development environment object in your config.json. Make sure not to commit or push it!

**Comment by CoreyWilson319** [comment]
![image](https://user-images.githubusercontent.com/72322079/99585052-ce2ef200-29b3-11eb-9a34-af276d0e03ba.png)
gives me this error when I fill those portions

**Comment by pmacaluso3** [comment]
Lemme see what you've got in there, just make sure to change your pw to some placeholder string

**Comment by CoreyWilson319** [comment]
![image](https://user-images.githubusercontent.com/72322079/99585326-2c5bd500-29b4-11eb-91e5-5f961fe3cec5.png)

**Comment by pmacaluso3** [comment]
Those values for username & password have got to be quoted strings

**Comment by CoreyWilson319** [comment]
Doesn't seem to care after adding qoutes

**Comment by CoreyWilson319** [comment]
Okay getting closer it doesn't like single quotes

**Comment by CoreyWilson319** [comment]
Is there a way to look and find my password, I don't use one to log into postgres

**Comment by pmacaluso3** [comment]
Try the password you use to unlock your machine at startup?

**Comment by CoreyWilson319** [comment]
Sorry yeah, I tried that but for whatever reason it wasn't working out. I ended up just changing the password in postgres and using that password worked. Thanks

**Comment by tylerdance** [comment]
<img width="1378" alt="Screen Shot 2020-11-18 at 4 20 23 PM" src="https://user-images.githubusercontent.com/72777766/99589494-0fc29b80-29ba-11eb-8b7e-48660538174d.png">
Getting an error in my psql that customer doesn't exist, but I don't see any errors in my terminal where I created the model

**Comment by pmacaluso3** [comment]
Try exiting and re-entering your psql session?

**Comment by tylerdance** [comment]
Yes thank you, sorry should've tried that.. sigh
