### ISSUE TITLE
Thursday, November 19, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#6]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by NikkiHmltn** [comment]
<img width="898" alt="Screen Shot 2020-11-19 at 11 33 28 AM" src="https://user-images.githubusercontent.com/65046641/99715020-2f5dd080-2a5b-11eb-9d5b-24ff8de4916a.png">
It's not letting me do git init anymore. Thought I misspelled it. I have no json files now. Should I delete and redo it?

**Comment by canourrea23** [comment]
![Screen Shot 2020-11-19 at 2 35 51 PM](https://user-images.githubusercontent.com/73137943/99715294-a5bafc80-2a74-11eb-97c6-a0e0fc39ff44.png)

**Comment by mkzarra** [comment]
> It's not letting me do git init anymore. Thought I misspelled it. I have no json files now. Should I delete and redo it?

Resolved
