### ISSUE TITLE
Friday, November 20, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#7]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by maddevred** [comment]
@romebell 
![Screenshot from 2020-11-20 16-10-43](https://user-images.githubusercontent.com/73178321/99850294-1df3f180-2b4b-11eb-8d52-ba81b1693b6b.png)
![Screenshot from 2020-11-20 16-10-56](https://user-images.githubusercontent.com/73178321/99850296-1fbdb500-2b4b-11eb-893f-e2fe03f13baf.png)

**Comment by maddevred** [comment]
@romebell restarted my terminal ![Screenshot from 2020-11-20 16-22-46](https://user-images.githubusercontent.com/73178321/99851149-ab841100-2b4c-11eb-819a-a4ef534f07b0.png)

**Comment by maddevred** [comment]
@romebell could you go back over what to do when you see this now that i got my server running? 
![Screenshot from 2020-11-20 16-29-41](https://user-images.githubusercontent.com/73178321/99851842-cd31c800-2b4d-11eb-9b62-62ec4bf52d06.png)

**Comment by romebell** [comment]
@marjames98 Make sure that you have `dotenv` installed by
```text
npm i dotenv
```

Also, at the top of your `index.js` file, you need to put 
```js
require('dotenv').config();

// other code below
const express = require('express');
...
...
...
```
